###
GET http://localhost:3000/productos/

###
POST http://localhost:3000/productos/
Content-Type: application/json

{
  "nombre": "Monitor",
  "precio": 600,
  "stock": 70,
  "estado": "disponible"
}

###
PATCH http://localhost:3000/productos/895fb1a6-50d5-447e-a4eb-608981bba86f
Content-Type: application/json

{
  "nombre": "Mouse editado",
  "estado": "No disponible"
}

###
DELETE http://localhost:3000/productos/97428a1f-72d1-4dbb-a46f-15823249ca01